sudo: required
dist: trusty
language: go
go:
  - 1.13.x
install:
  - sudo apt-get update
  - sudo apt-get install opencl-headers nvidia-opencl-dev
  - go get -v github.com/golangci/golangci-lint/cmd/golangci-lint
script:
  - export GO111MODULE=on
  - go build -tags opencl
  - ./goclean.sh
